name: Promote docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Promote docs to Public Branch
        run: |
          git config --global user.email "palkokec@gmail.com"
          git config --global user.name "Pali Promoter"
          git clone -b public git@github.com:palkokec/romani-chib.git
          cd romani-chib
          rm -rf ./*
          rsync -avh --progress --delete ../docs .
          git add *
          git commit -m "Promote docs to public branch"
          git push origin public
