name: Promote docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Promote to Public Branch
        run: |
          git checkout -b public
          git config --global user.email "palkokec@gmail.com"
          git config --global user.name "Pali Promoter"
          git add docs/*
          git commit -m "Promote docs to public branch"
          git push origin public
